steps:
  #Create .env file from Google Cloud Build substitution variables
  - name: node
    entrypoint: npm
    args: ["run", "create-env"]
    env:
      - "VITE_CONTENTFUL_DELIVERY_TOKEN=${_CONTENTFUL_DELIVERY_TOKEN}"
      - "VITE_CONTENTFUL_SPACE_ID=${_CONTENTFUL_SPACE_ID}"
  #The .env file is prepared and ready to deploy to Google App Engine

  #Create the Container using a Dockerfile
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:$COMMIT_SHA",
        ".",
      ]
images:
  - "${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:$COMMIT_SHA"
timeout: "1600s"
